// Generate the Filmtone Finish signing key pairs (full + trial).
// Usage: bun run scripts/license/keygen.ts [--out-dir <dir>]
// Private keys are written OUTSIDE the repo, by default to ~/.filmtone/secrets —
// deliberately NOT under ~/Documents, which macOS may sync to iCloud. Back both
// key files up to 1Password immediately. Never commit them.

import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  KEY_FILE_SCHEMA,
  type KeyFile,
  type LicenseKind,
  bytesToHex,
  isoNow,
} from "./core.ts";

function parseArgs(argv: string[]): { outDir: string } {
  const home = process.env.HOME ?? "";
  const queue = [...argv];
  let outDir = join(home, ".filmtone", "secrets");
  while (queue.length > 0) {
    const flag = queue.shift() as string;
    if (flag !== "--out-dir") throw new Error(`unexpected argument: ${flag}`);
    const value = queue.shift();
    if (!value) throw new Error("--out-dir requires a value");
    outDir = value;
  }
  if (!outDir) throw new Error("could not resolve output directory");
  return { outDir };
}

async function generateKeyFile(role: LicenseKind): Promise<KeyFile> {
  const pair = (await crypto.subtle.generateKey({ name: "Ed25519" }, true, [
    "sign",
    "verify",
  ])) as CryptoKeyPair;
  const pkcs8 = new Uint8Array(await crypto.subtle.exportKey("pkcs8", pair.privateKey));
  const rawPub = new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey));
  return {
    schema: KEY_FILE_SCHEMA,
    role,
    createdAt: isoNow(),
    privateKeyPkcs8Hex: bytesToHex(pkcs8),
    publicKeyRawHex: bytesToHex(rawPub),
  };
}

function cHexArray(hex: string): string {
  const bytes = hex.match(/.{2}/g) ?? [];
  return bytes.map((b) => `0x${b}`).join(", ");
}

const { outDir } = parseArgs(process.argv.slice(2));
mkdirSync(outDir, { recursive: true, mode: 0o700 });
chmodSync(outDir, 0o700);

const targets: Array<{ role: LicenseKind; file: string }> = [
  { role: "full", file: join(outDir, "filmtone-full.key.json") },
  { role: "trial", file: join(outDir, "filmtone-trial.key.json") },
];

const existing = targets.filter((t) => existsSync(t.file));
if (existing.length > 0) {
  console.error("Refusing to overwrite existing key files:");
  for (const t of existing) console.error(`  ${t.file}`);
  console.error("Move them away manually if you intend to rotate keys.");
  process.exit(1);
}

const generated: Array<{ role: LicenseKind; file: string; publicKeyRawHex: string }> = [];
for (const target of targets) {
  const keyFile = await generateKeyFile(target.role);
  // flag "wx" makes the overwrite refusal atomic (no exists->write race).
  writeFileSync(target.file, `${JSON.stringify(keyFile, null, 2)}\n`, { mode: 0o600, flag: "wx" });
  chmodSync(target.file, 0o600);
  generated.push({ role: target.role, file: target.file, publicKeyRawHex: keyFile.publicKeyRawHex });
}

const fullPub = generated.find((g) => g.role === "full")?.publicKeyRawHex ?? "";
const trialPub = generated.find((g) => g.role === "trial")?.publicKeyRawHex ?? "";
const snippetPath = join(outDir, "PublicKeys.h.snippet");
writeFileSync(
  snippetPath,
  [
    "// Generated by scripts/license/keygen.ts — public keys only (safe to embed).",
    `// Generated at ${isoNow()}`,
    "#pragma once",
    "#include <cstdint>",
    "",
    `static const uint8_t kFilmtoneFullPublicKey[32] = {${cHexArray(fullPub)}};`,
    `static const uint8_t kFilmtoneTrialPublicKey[32] = {${cHexArray(trialPub)}};`,
    "",
  ].join("\n"),
);

console.log("Key pairs generated (private keys are NOT printed):");
for (const g of generated) {
  console.log(`  [${g.role}]  ${g.file}`);
  console.log(`          public key (raw hex): ${g.publicKeyRawHex}`);
}
console.log(`  C header snippet: ${snippetPath}`);
console.log("Next: back up both .key.json files to 1Password now.");
