/**
 * bundle-depth-probe.ts — emit a TS module with base64-encoded depth PNGs
 * so the shared FilmLabCanvas can preload the depth probe without any
 * asset-server plumbing. Dev-only.
 *
 * Usage:
 *   cd packages/film-lab-renderer
 *   bun run dev-scripts/bundle-depth-probe.ts
 *
 * Output:
 *   packages/film-lab-ui/src/dev-depth-probe-data.ts
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';

const scriptDir = dirname(new URL(import.meta.url).pathname);
const fixturesDir = resolve(scriptDir, '..', 'dev-fixtures');
const framesDir = resolve(fixturesDir, 'frames');
const outPath = resolve(scriptDir, '..', '..', 'film-lab-ui', 'src', 'dev-depth-probe-data.ts');

// Prefer per-frame depth (dev-fixtures/frames/depth-NNN.png — matches every
// video frame 1:1 so there's no "ghost hand" between keyframes). Fall back
// to the older 10-keyframe set if per-frame isn't available.
let files: string[];
let baseDir: string;
let perFrame: boolean;
try {
  files = readdirSync(framesDir)
    .filter((f) => /^depth-\d+\.png$/.test(f))
    .sort();
  if (files.length === 0) throw new Error('empty');
  baseDir = framesDir;
  perFrame = true;
} catch {
  files = readdirSync(fixturesDir)
    .filter((f) => /^depth-probe-depth-\d+\.png$/.test(f))
    .sort();
  if (files.length === 0) throw new Error('No depth PNGs found');
  baseDir = fixturesDir;
  perFrame = false;
}

const uris = files.map((f) => {
  const buf = readFileSync(join(baseDir, f));
  return `data:image/png;base64,${buf.toString('base64')}`;
});

const ts =
  `// AUTO-GENERATED by packages/film-lab-renderer/dev-scripts/bundle-depth-probe.ts\n` +
  `// Source: ${perFrame ? 'dev-fixtures/frames/depth-*.png (per-frame)' : 'dev-fixtures/depth-probe-depth-*.png (keyframes)'}\n` +
  `// Dev-only. Do not commit to a public release without review.\n\n` +
  `export const DEV_DEPTH_PROBE_PER_FRAME = ${perFrame ? 'true' : 'false'};\n` +
  `export const DEV_DEPTH_PROBE_KEYFRAME_STRIDE = ${perFrame ? '1' : '15'};\n` +
  `export const DEV_DEPTH_PROBE_FPS = 25;\n\n` +
  `export const DEV_DEPTH_PROBE_DATA_URIS: ReadonlyArray<string> = [\n` +
  uris.map((u) => `  ${JSON.stringify(u)},`).join('\n') +
  `\n];\n`;

writeFileSync(outPath, ts);
console.log(`Wrote ${files.length} data URIs to ${outPath}`);
