import Foundation

enum FilmtonePhase0Generated {
    static let schemaVersion = 2
    static let presetVersion = "v1"
    static let presetDefault = "cinematic"
    static let presetStrengthDefault = 1.0
    static let paramKeys: [String] = ["exposure", "contrast", "saturation", "temperature", "tint", "rgbShift", "lensSoftness", "grainRadialMix", "grainSize", "bloomThreshold", "bloomStrength", "bloomRadius", "diffusion", "halationIntensity", "halationSpread", "halationHue", "halationThreshold", "halationRadius", "bloomSoftKnee", "halationSoftKnee", "compressionAmount", "compressionRange", "fade", "vignette", "grainIntensity"]
    static let quickAxisIds: [String] = ["filmCharacter", "era", "dynamics"]
    static let quickAxisMin = -1.0
    static let quickAxisMax = 1.0
    static let quickAxisStep = 0.01
    static let defaultQuickState = FilmtoneQuickState(
        filmCharacter: 0.0,
        era: 0.0,
        dynamics: 0.0
    )
    static let outputProfile = Phase0OutputProfileDTO(
        longEdge: 1920,
        fps: 30,
        codec: "h264",
        container: "mp4",
        preserveAudio: true
    )
    static let rgbShiftMax = 0.005
    static let sourceDurationCapSec = 300.0
    static let sourceLongEdgeCap = 3840
    static let sourceFileSizeCapBytes = 8589934592
    static let resetParams: FilmtonePhase0Params =
    .init(
            exposure: 0.0,
            contrast: 1.0,
            saturation: 1.0,
            temperature: 0.0,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.3,
            bloomThreshold: 0.8,
            bloomStrength: 0.0,
            bloomRadius: 0.4,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.6,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.0,
            vignette: 0.0,
            grainIntensity: 0.0
        )
    static let paramsByName: [String: FilmtonePhase0Params] = [
        "reset": .init(
            exposure: 0.0,
            contrast: 1.0,
            saturation: 1.0,
            temperature: 0.0,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.3,
            bloomThreshold: 0.8,
            bloomStrength: 0.0,
            bloomRadius: 0.4,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.6,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.0,
            vignette: 0.0,
            grainIntensity: 0.0
        ),
        "cinematic": .init(
            exposure: 0.09,
            contrast: 1.24,
            saturation: 0.87,
            temperature: -0.11,
            tint: 0.0,
            rgbShift: 0.002,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.32,
            bloomThreshold: 0.76,
            bloomStrength: 0.26,
            bloomRadius: 0.5,
            diffusion: 0.1,
            halationIntensity: 0.06,
            halationSpread: 20.0,
            halationHue: 18.0,
            halationThreshold: 0.6,
            halationRadius: 0.4,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.025,
            vignette: 0.32,
            grainIntensity: 0.09
        ),
        "portra": .init(
            exposure: 0.2,
            contrast: 1.1,
            saturation: 0.9,
            temperature: 0.1,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.35,
            bloomThreshold: 0.78,
            bloomStrength: 0.14,
            bloomRadius: 0.38,
            diffusion: 0.05,
            halationIntensity: 0.18,
            halationSpread: 20.0,
            halationHue: 28.0,
            halationThreshold: 0.6,
            halationRadius: 0.44,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.05,
            vignette: 0.2,
            grainIntensity: 0.14
        ),
        "gold200": .init(
            exposure: 0.15,
            contrast: 1.2,
            saturation: 1.15,
            temperature: 0.18,
            tint: 0.0,
            rgbShift: 0.0012,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.3,
            bloomThreshold: 0.8,
            bloomStrength: 0.16,
            bloomRadius: 0.35,
            diffusion: 0.04,
            halationIntensity: 0.12,
            halationSpread: 18.0,
            halationHue: 32.0,
            halationThreshold: 0.6,
            halationRadius: 0.4,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.03,
            vignette: 0.25,
            grainIntensity: 0.12
        ),
        "pro400h": .init(
            exposure: 0.25,
            contrast: 1.05,
            saturation: 0.85,
            temperature: -0.1,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.28,
            bloomThreshold: 0.84,
            bloomStrength: 0.06,
            bloomRadius: 0.42,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.08,
            vignette: 0.15,
            grainIntensity: 0.075
        ),
        "bw": .init(
            exposure: 0.1,
            contrast: 1.4,
            saturation: 0.0,
            temperature: 0.0,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.45,
            bloomThreshold: 0.8,
            bloomStrength: 0.16,
            bloomRadius: 0.52,
            diffusion: 0.04,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.02,
            vignette: 0.5,
            grainIntensity: 0.18
        ),
        "ektar100": .init(
            exposure: 0.05,
            contrast: 1.25,
            saturation: 1.3,
            temperature: 0.02,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.15,
            bloomThreshold: 0.86,
            bloomStrength: 0.08,
            bloomRadius: 0.28,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.0,
            vignette: 0.15,
            grainIntensity: 0.05
        ),
        "superia400": .init(
            exposure: 0.1,
            contrast: 1.18,
            saturation: 1.08,
            temperature: -0.08,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.4,
            bloomThreshold: 0.8,
            bloomStrength: 0.08,
            bloomRadius: 0.32,
            diffusion: 0.0,
            halationIntensity: 0.08,
            halationSpread: 15.0,
            halationHue: 14.0,
            halationThreshold: 0.6,
            halationRadius: 0.32,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.04,
            vignette: 0.2,
            grainIntensity: 0.115
        ),
        "cinestill800t": .init(
            exposure: 0.15,
            contrast: 1.15,
            saturation: 0.95,
            temperature: -0.3,
            tint: 0.0,
            rgbShift: 0.00115,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.6,
            bloomThreshold: 0.64,
            bloomStrength: 0.4,
            bloomRadius: 0.6,
            diffusion: 0.16,
            halationIntensity: 0.14,
            halationSpread: 28.0,
            halationHue: 20.0,
            halationThreshold: 0.6,
            halationRadius: 0.56,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.03,
            vignette: 0.3,
            grainIntensity: 0.14
        ),
        "velvia50": .init(
            exposure: 0.0,
            contrast: 1.35,
            saturation: 1.45,
            temperature: 0.04,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.1,
            bloomThreshold: 0.9,
            bloomStrength: 0.04,
            bloomRadius: 0.28,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            fade: 0.0,
            vignette: 0.1,
            grainIntensity: 0.02
        )
    ]
    static let quickWeights: [String: [String: Double]] = [
        "filmCharacter": [
            "saturation": 0.24,
            "temperature": 0.16,
            "tint": -0.06,
            "grainIntensity": 0.22,
            "vignette": 0.12
        ],
        "era": [
            "fade": 0.18,
            "saturation": -0.14,
            "contrast": -0.08,
            "halationIntensity": 0.16,
            "halationSpread": 6.0
        ],
        "dynamics": [
            "exposure": 0.24,
            "contrast": 0.18,
            "bloomStrength": 0.16,
            "bloomThreshold": -0.06,
            "bloomRadius": 0.12
        ]
    ]
}
