import Foundation

enum FilmtonePhase0Generated {
    static let schemaVersion = 2
    static let presetVersion = "v1"
    static let presetDefault = "reset"
    static let presetStrengthDefault = 1.0
    static let paramKeys: [String] = ["exposure", "contrast", "saturation", "temperature", "tint", "rgbShift", "lensSoftness", "grainRadialMix", "grainSize", "bloomThreshold", "bloomStrength", "bloomRadius", "diffusion", "halationIntensity", "halationSpread", "halationHue", "halationThreshold", "halationRadius", "bloomSoftKnee", "halationSoftKnee", "compressionAmount", "compressionRange", "printContrast", "cyan", "magenta", "yellow", "fade", "vignette", "grainIntensity"]
    static let quickAxisIds: [String] = ["filmCharacter", "era", "dynamics"]
    static let quickAxisMin = -1.0
    static let quickAxisMax = 1.0
    static let quickAxisStep = 0.01
    static let defaultQuickState = FilmtoneQuickState(
        filmCharacter: 0.0,
        era: 0.0,
        dynamics: 0.0
    )
    static let outputProfile = Phase0OutputProfileDTO(
        longEdge: 1920,
        fps: 30,
        codec: "h264",
        container: "mp4",
        preserveAudio: true
    )
    static let rgbShiftMax = 0.005
    static let sourceDurationCapSec = 300.0
    static let sourceLongEdgeCap = 3840
    static let sourceFileSizeCapBytes = 8589934592
    static let resetParams: FilmtonePhase0Params =
    .init(
            exposure: 0.0,
            contrast: 1.0,
            saturation: 1.0,
            temperature: 0.0,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.3,
            bloomThreshold: 0.8,
            bloomStrength: 0.0,
            bloomRadius: 0.4,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.6,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            printContrast: 0.0,
            cyan: 0.0,
            magenta: 0.0,
            yellow: 0.0,
            fade: 0.0,
            vignette: 0.0,
            grainIntensity: 0.0
        )
    static let paramsByName: [String: FilmtonePhase0Params] = [
        "reset": .init(
            exposure: 0.0,
            contrast: 1.0,
            saturation: 1.0,
            temperature: 0.0,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.3,
            bloomThreshold: 0.72,
            bloomStrength: 0.22,
            bloomRadius: 0.52,
            diffusion: 0.08,
            halationIntensity: 0.1,
            halationSpread: 22.0,
            halationHue: 20.0,
            halationThreshold: 0.6,
            halationRadius: 0.44,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            printContrast: 0.0,
            cyan: 0.0,
            magenta: 0.0,
            yellow: 0.0,
            fade: 0.0,
            vignette: 0.0,
            grainIntensity: 0.0
        ),
        "cinematic": .init(
            exposure: 0.09,
            contrast: 1.24,
            saturation: 0.87,
            temperature: -0.11,
            tint: 0.0,
            rgbShift: 0.001,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.32,
            bloomThreshold: 0.78,
            bloomStrength: 0.18,
            bloomRadius: 0.42,
            diffusion: 0.05,
            halationIntensity: 0.02,
            halationSpread: 18.0,
            halationHue: 18.0,
            halationThreshold: 0.6,
            halationRadius: 0.36,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.08,
            compressionRange: 0.5,
            printContrast: 0.08,
            cyan: 0.0,
            magenta: 0.0,
            yellow: 0.0,
            fade: 0.025,
            vignette: 0.32,
            grainIntensity: 0.09
        ),
        "portra": .init(
            exposure: 0.2,
            contrast: 1.04,
            saturation: 0.86,
            temperature: 0.14,
            tint: 0.03,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.32,
            bloomThreshold: 0.78,
            bloomStrength: 0.1,
            bloomRadius: 0.38,
            diffusion: 0.04,
            halationIntensity: 0.08,
            halationSpread: 20.0,
            halationHue: 28.0,
            halationThreshold: 0.6,
            halationRadius: 0.44,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.08,
            compressionRange: 0.5,
            printContrast: 0.0,
            cyan: 0.0,
            magenta: 0.04,
            yellow: 0.06,
            fade: 0.05,
            vignette: 0.2,
            grainIntensity: 0.12
        ),
        "gold200": .init(
            exposure: 0.15,
            contrast: 1.25,
            saturation: 1.22,
            temperature: 0.23,
            tint: 0.0,
            rgbShift: 0.0012,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.28,
            bloomThreshold: 0.8,
            bloomStrength: 0.11,
            bloomRadius: 0.35,
            diffusion: 0.04,
            halationIntensity: 0.06,
            halationSpread: 18.0,
            halationHue: 32.0,
            halationThreshold: 0.6,
            halationRadius: 0.4,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            printContrast: 0.1,
            cyan: -0.05,
            magenta: 0.0,
            yellow: 0.07,
            fade: 0.03,
            vignette: 0.27,
            grainIntensity: 0.12
        ),
        "pro400h": .init(
            exposure: 0.31,
            contrast: 0.98,
            saturation: 0.82,
            temperature: -0.15,
            tint: -0.03,
            rgbShift: 0.0,
            lensSoftness: 0.06,
            grainRadialMix: 1.0,
            grainSize: 0.25,
            bloomThreshold: 0.84,
            bloomStrength: 0.06,
            bloomRadius: 0.42,
            diffusion: 0.03,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.06,
            compressionRange: 0.5,
            printContrast: 0.0,
            cyan: 0.02,
            magenta: -0.05,
            yellow: -0.03,
            fade: 0.11,
            vignette: 0.1,
            grainIntensity: 0.06
        ),
        "bw": .init(
            exposure: 0.1,
            contrast: 1.5,
            saturation: 0.0,
            temperature: 0.0,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.4,
            bloomThreshold: 0.8,
            bloomStrength: 0.08,
            bloomRadius: 0.52,
            diffusion: 0.02,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.08,
            compressionRange: 0.5,
            printContrast: 0.14,
            cyan: 0.0,
            magenta: 0.0,
            yellow: 0.0,
            fade: 0.0,
            vignette: 0.56,
            grainIntensity: 0.16
        ),
        "ektar100": .init(
            exposure: 0.03,
            contrast: 1.32,
            saturation: 1.38,
            temperature: 0.05,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.12,
            bloomThreshold: 0.9,
            bloomStrength: 0.03,
            bloomRadius: 0.28,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            printContrast: 0.14,
            cyan: 0.0,
            magenta: 0.0,
            yellow: 0.0,
            fade: 0.0,
            vignette: 0.18,
            grainIntensity: 0.035
        ),
        "superia400": .init(
            exposure: 0.13,
            contrast: 1.18,
            saturation: 1.06,
            temperature: -0.12,
            tint: -0.04,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.44,
            bloomThreshold: 0.8,
            bloomStrength: 0.06,
            bloomRadius: 0.32,
            diffusion: 0.0,
            halationIntensity: 0.05,
            halationSpread: 15.0,
            halationHue: 14.0,
            halationThreshold: 0.6,
            halationRadius: 0.32,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.05,
            compressionRange: 0.5,
            printContrast: 0.06,
            cyan: 0.02,
            magenta: -0.07,
            yellow: -0.02,
            fade: 0.07,
            vignette: 0.2,
            grainIntensity: 0.13
        ),
        "cinestill800t": .init(
            exposure: 0.11,
            contrast: 1.15,
            saturation: 0.92,
            temperature: -0.34,
            tint: 0.0,
            rgbShift: 0.0015,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.58,
            bloomThreshold: 0.7,
            bloomStrength: 0.24,
            bloomRadius: 0.52,
            diffusion: 0.1,
            halationIntensity: 0.06,
            halationSpread: 20.0,
            halationHue: 20.0,
            halationThreshold: 0.65,
            halationRadius: 0.46,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            printContrast: 0.08,
            cyan: 0.03,
            magenta: 0.0,
            yellow: -0.03,
            fade: 0.03,
            vignette: 0.3,
            grainIntensity: 0.15
        ),
        "velvia50": .init(
            exposure: 0.0,
            contrast: 1.43,
            saturation: 1.53,
            temperature: 0.02,
            tint: 0.0,
            rgbShift: 0.0,
            lensSoftness: 0.0,
            grainRadialMix: 1.0,
            grainSize: 0.08,
            bloomThreshold: 0.95,
            bloomStrength: 0.01,
            bloomRadius: 0.28,
            diffusion: 0.0,
            halationIntensity: 0.0,
            halationSpread: 15.0,
            halationHue: 0.0,
            halationThreshold: 0.6,
            halationRadius: 0.3,
            bloomSoftKnee: 0.5,
            halationSoftKnee: 0.3,
            compressionAmount: 0.0,
            compressionRange: 0.5,
            printContrast: 0.16,
            cyan: 0.0,
            magenta: 0.0,
            yellow: 0.0,
            fade: 0.0,
            vignette: 0.12,
            grainIntensity: 0.01
        )
    ]
    static let hiddenDefaults = FilmtonePhase0HiddenDefaults(
        depthMistGain: 0.0,
        depthGlowGain: 0.0,
        depthRayAngleGamma: 1.4,
        depthRayAngleInnerThreshold: 0.1,
        depthMistRayAngleGain: 0.35,
        depthBloomRayAngleGain: 0.25,
        depthHalationRayAngleGain: 0.18,
        depthMistFieldPsfGain: 1.0,
        depthBloomFieldPsfGain: 1.0,
        depthHalationFieldPsfGain: 1.0,
        depthMistFieldPsfRadiusPx: 18.0,
        depthBloomFieldPsfRadiusPx: 9.0,
        depthHalationFieldPsfRadiusPx: 12.0,
        crossFilterDepthGain: 0.25,
        crossFilterAngleGain: 0.35,
        crossFilterAngleGamma: 1.4,
        crossFilterAngleInnerThreshold: 0.1,
        crossFilterEdgeLengthGain: 0.45,
        crossFilterEdgeStrengthGain: 0.25
    )
    static let quickWeights: [String: [String: Double]] = [
        "filmCharacter": [
            "saturation": 0.24,
            "temperature": 0.16,
            "tint": -0.06,
            "grainIntensity": 0.22,
            "vignette": 0.12
        ],
        "era": [
            "fade": 0.18,
            "saturation": -0.14,
            "contrast": -0.08,
            "halationIntensity": 0.16,
            "halationSpread": 6.0
        ],
        "dynamics": [
            "exposure": 0.24,
            "contrast": 0.18,
            "bloomStrength": 0.16,
            "bloomThreshold": -0.06,
            "bloomRadius": 0.12
        ]
    ]
}
