import Foundation

// v1.3 Camera Profiles Phase B-3 (V-Log) and Phase C (S-Log3) accuracy gate.
// Loads the reference fixtures generated by the per-curve `encode-ramp.py`
// scripts and asserts that `FilmtoneSourceProfileMath` matches them within
// the D-CP5 tolerance budget. A drift beyond budget MUST fail this script
// (silent fallback / fixture regeneration in CI is forbidden — the fixture
// is only regenerated locally and committed).

// MARK: - Test harness

struct SourceProfileMathCheckError: LocalizedError {
    let message: String
    var errorDescription: String? { message }
}

func expect(_ condition: @autoclosure () -> Bool, _ message: String) throws {
    if !condition() {
        throw SourceProfileMathCheckError(message: message)
    }
}

// MARK: - Fixture decode

private struct LinearizationSample: Decodable {
    let vEncoded: Double
    let lLinear: Double
}

private struct DlogMacbethPatch: Decodable {
    let index: Int
    let dlogEncoded: [Double]
    let rec709EncodedExpected: [Double]
    let rec709LinearReference: [Double]
}

private struct ClogMacbethPatch: Decodable {
    let index: Int
    let clogEncoded: [Double]
    let rec709EncodedExpected: [Double]
    let rec709LinearReference: [Double]
}

private struct Clog3CineGamutMacbethPatch: Decodable {
    let index: Int
    let clog3Encoded: [Double]
    let rec709EncodedExpected: [Double]
    let rec709LinearReference: [Double]
}

private struct DlogMMacbethPatch: Decodable {
    let index: Int
    let dlogMEncoded: [Double]
    let rec709EncodedExpected: [Double]
    let rec709LinearReference: [Double]
}

private struct MacbethPatch: Decodable {
    let index: Int
    let vlogEncoded: [Double]
    let rec709EncodedExpected: [Double]
    let rec709LinearReference: [Double]
}

private struct Slog3MacbethPatch: Decodable {
    let index: Int
    let slog3Encoded: [Double]
    let rec709EncodedExpected: [Double]
    let rec709LinearReference: [Double]
}

private func loadJSON<T: Decodable>(_ url: URL, as type: T.Type = T.self) throws -> T {
    let data = try Data(contentsOf: url)
    return try JSONDecoder().decode(T.self, from: data)
}

// MARK: - Color science helpers (independent of Filmtone)

/// Convert linear sRGB / Rec.709 to CIE XYZ (D65). The matrix is the
/// IEC 61966-2-1 standard linear transformation; it lives here so the
/// test isn't tied to colour-science Python at runtime.
private func rec709LinearToXYZ(_ rgb: (r: Double, g: Double, b: Double)) -> (X: Double, Y: Double, Z: Double) {
    let X = 0.4124564 * rgb.r + 0.3575761 * rgb.g + 0.1804375 * rgb.b
    let Y = 0.2126729 * rgb.r + 0.7151522 * rgb.g + 0.0721750 * rgb.b
    let Z = 0.0193339 * rgb.r + 0.1191920 * rgb.g + 0.9503041 * rgb.b
    return (X, Y, Z)
}

/// CIE XYZ -> CIELAB (D65). Reference white is the IEC 61966-2-1 D65
/// (95.047, 100.000, 108.883).
private func xyzToLab(_ xyz: (X: Double, Y: Double, Z: Double)) -> (L: Double, a: Double, b: Double) {
    let xn = 95.047, yn = 100.0, zn = 108.883
    let fx = labF(xyz.X * 100.0 / xn)
    let fy = labF(xyz.Y * 100.0 / yn)
    let fz = labF(xyz.Z * 100.0 / zn)
    let L = 116.0 * fy - 16.0
    let a = 500.0 * (fx - fy)
    let b = 200.0 * (fy - fz)
    return (L, a, b)
}

private func labF(_ t: Double) -> Double {
    let delta = 6.0 / 29.0
    if t > pow(delta, 3) {
        return pow(t, 1.0 / 3.0)
    }
    return t / (3.0 * delta * delta) + 4.0 / 29.0
}

/// CIE ΔE2000 between two L*a*b* triples. Implementation follows Sharma
/// et al. 2005 (sample code in §5). Tested against published reference
/// values inline below.
private func deltaE2000(
    _ lab1: (L: Double, a: Double, b: Double),
    _ lab2: (L: Double, a: Double, b: Double)
) -> Double {
    let kL = 1.0, kC = 1.0, kH = 1.0
    let L1 = lab1.L; let a1 = lab1.a; let b1 = lab1.b
    let L2 = lab2.L; let a2 = lab2.a; let b2 = lab2.b
    let C1 = sqrt(a1 * a1 + b1 * b1)
    let C2 = sqrt(a2 * a2 + b2 * b2)
    let cBar = (C1 + C2) / 2.0
    let g = 0.5 * (1.0 - sqrt(pow(cBar, 7) / (pow(cBar, 7) + pow(25.0, 7))))
    let a1p = a1 * (1.0 + g)
    let a2p = a2 * (1.0 + g)
    let C1p = sqrt(a1p * a1p + b1 * b1)
    let C2p = sqrt(a2p * a2p + b2 * b2)
    let h1p = atan2deg(b1, a1p)
    let h2p = atan2deg(b2, a2p)

    let dLp = L2 - L1
    let dCp = C2p - C1p
    var dhp: Double
    if C1p * C2p == 0 {
        dhp = 0
    } else if abs(h2p - h1p) <= 180 {
        dhp = h2p - h1p
    } else if h2p - h1p > 180 {
        dhp = h2p - h1p - 360
    } else {
        dhp = h2p - h1p + 360
    }
    let dHp = 2.0 * sqrt(C1p * C2p) * sin(dhp.radians / 2.0)

    let LBar = (L1 + L2) / 2.0
    let CBar = (C1p + C2p) / 2.0
    var hBar: Double
    if C1p * C2p == 0 {
        hBar = h1p + h2p
    } else if abs(h1p - h2p) <= 180 {
        hBar = (h1p + h2p) / 2.0
    } else if h1p + h2p < 360 {
        hBar = (h1p + h2p + 360) / 2.0
    } else {
        hBar = (h1p + h2p - 360) / 2.0
    }
    let T = 1.0
        - 0.17 * cos((hBar - 30).radians)
        + 0.24 * cos((2 * hBar).radians)
        + 0.32 * cos((3 * hBar + 6).radians)
        - 0.20 * cos((4 * hBar - 63).radians)
    let dTheta = 30.0 * exp(-pow((hBar - 275) / 25.0, 2))
    let RC = 2.0 * sqrt(pow(CBar, 7) / (pow(CBar, 7) + pow(25.0, 7)))
    let SL = 1.0 + (0.015 * pow(LBar - 50, 2)) / sqrt(20 + pow(LBar - 50, 2))
    let SC = 1.0 + 0.045 * CBar
    let SH = 1.0 + 0.015 * CBar * T
    let RT = -sin((2.0 * dTheta).radians) * RC

    let dE = sqrt(
        pow(dLp / (kL * SL), 2)
        + pow(dCp / (kC * SC), 2)
        + pow(dHp / (kH * SH), 2)
        + RT * (dCp / (kC * SC)) * (dHp / (kH * SH))
    )
    return dE
}

private func atan2deg(_ y: Double, _ x: Double) -> Double {
    var deg = atan2(y, x) * 180.0 / Double.pi
    if deg < 0 { deg += 360 }
    return deg
}

private extension Double {
    var radians: Double { self * Double.pi / 180.0 }
}

// MARK: - DJI D-Log accuracy gate

private func runDlogLinearizationCheck(fixtureURL: URL) throws {
    let samples: [LinearizationSample] = try loadJSON(fixtureURL.appendingPathComponent("linearization-ramp.json"))
    try expect(samples.count == 4096, "D-Log linearization ramp expected 4096 samples, got \(samples.count)")
    var maxDelta = 0.0
    for sample in samples {
        let computed = FilmtoneSourceProfileMath.dlogDecode(sample.vEncoded)
        maxDelta = max(maxDelta, abs(computed - sample.lLinear))
    }
    try expect(
        maxDelta <= 1e-3,
        "D-Log linearization drift max |Δ| = \(maxDelta) exceeds tolerance 1e-3"
    )
    print(String(format: "    D-Log linearization max |Δ| = %.6f (budget 1e-3)", maxDelta))
}

private func runDlogMacbethCheck(fixtureURL: URL) throws {
    let patches: [DlogMacbethPatch] = try loadJSON(fixtureURL.appendingPathComponent("macbeth-patches.json"))
    try expect(patches.count == 24, "D-Log Macbeth fixture expected 24 patches, got \(patches.count)")

    var maxDeltaE = 0.0
    var sumDeltaE = 0.0
    var maxFullFrame = 0.0
    var sumFullFrame = 0.0
    var fullFrameCount = 0

    for patch in patches {
        let computed = FilmtoneSourceProfileMath.dlogPixelToRec709(
            red: patch.dlogEncoded[0],
            green: patch.dlogEncoded[1],
            blue: patch.dlogEncoded[2]
        )

        let computedLinear = (
            r: rec709InverseEncode(computed.red),
            g: rec709InverseEncode(computed.green),
            b: rec709InverseEncode(computed.blue)
        )
        let expectedLinear = (
            r: rec709InverseEncode(patch.rec709EncodedExpected[0]),
            g: rec709InverseEncode(patch.rec709EncodedExpected[1]),
            b: rec709InverseEncode(patch.rec709EncodedExpected[2])
        )
        let lab1 = xyzToLab(rec709LinearToXYZ(computedLinear))
        let lab2 = xyzToLab(rec709LinearToXYZ(expectedLinear))
        let dE = deltaE2000(lab1, lab2)
        maxDeltaE = max(maxDeltaE, dE)
        sumDeltaE += dE

        for ch in 0..<3 {
            let drift = abs(channel(computed, ch) - patch.rec709EncodedExpected[ch]) * 255.0
            maxFullFrame = max(maxFullFrame, drift)
            sumFullFrame += drift
            fullFrameCount += 1
        }
    }
    let meanDeltaE = sumDeltaE / Double(patches.count)
    let meanFullFrame = sumFullFrame / Double(fullFrameCount)

    try expect(maxDeltaE <= 2.0, "D-Log Macbeth ΔE2000 max = \(maxDeltaE) exceeds budget 2.0")
    try expect(meanDeltaE <= 1.0, "D-Log Macbeth ΔE2000 mean = \(meanDeltaE) exceeds budget 1.0")
    try expect(maxFullFrame <= 2.0, "D-Log full-frame max = \(maxFullFrame)/255 exceeds budget 2/255")
    try expect(meanFullFrame <= 0.5, "D-Log full-frame mean = \(meanFullFrame)/255 exceeds budget 0.5/255")
    print(String(format: "    D-Log Macbeth ΔE2000 max = %.3f mean = %.3f (budget 2.0/1.0)", maxDeltaE, meanDeltaE))
    print(String(format: "    D-Log Macbeth full-frame max = %.3f mean = %.3f /255 (budget 2.0/0.5)", maxFullFrame, meanFullFrame))
}

// MARK: - DJI D-Log M accuracy gate

private func runDlogMLinearizationCheck(fixtureURL: URL) throws {
    let samples: [LinearizationSample] = try loadJSON(fixtureURL.appendingPathComponent("linearization-ramp.json"))
    try expect(samples.count == 4096, "D-Log M linearization ramp expected 4096 samples, got \(samples.count)")
    var maxDelta = 0.0
    for sample in samples {
        let computed = FilmtoneSourceProfileMath.dlogMDecode(sample.vEncoded)
        maxDelta = max(maxDelta, abs(computed - sample.lLinear))
    }
    try expect(
        maxDelta <= 1e-3,
        "D-Log M linearization drift max |Δ| = \(maxDelta) exceeds tolerance 1e-3"
    )
    print(String(format: "    D-Log M linearization max |Δ| = %.6f (budget 1e-3)", maxDelta))
}

private func runDlogMMacbethCheck(fixtureURL: URL) throws {
    let patches: [DlogMMacbethPatch] = try loadJSON(fixtureURL.appendingPathComponent("macbeth-patches.json"))
    try expect(patches.count == 24, "D-Log M Macbeth fixture expected 24 patches, got \(patches.count)")

    var maxDeltaE = 0.0
    var sumDeltaE = 0.0
    var maxFullFrame = 0.0
    var sumFullFrame = 0.0
    var fullFrameCount = 0

    for patch in patches {
        let computed = FilmtoneSourceProfileMath.dlogMPixelToRec709(
            red: patch.dlogMEncoded[0],
            green: patch.dlogMEncoded[1],
            blue: patch.dlogMEncoded[2]
        )

        let computedLinear = (
            r: rec709InverseEncode(computed.red),
            g: rec709InverseEncode(computed.green),
            b: rec709InverseEncode(computed.blue)
        )
        let expectedLinear = (
            r: rec709InverseEncode(patch.rec709EncodedExpected[0]),
            g: rec709InverseEncode(patch.rec709EncodedExpected[1]),
            b: rec709InverseEncode(patch.rec709EncodedExpected[2])
        )
        let lab1 = xyzToLab(rec709LinearToXYZ(computedLinear))
        let lab2 = xyzToLab(rec709LinearToXYZ(expectedLinear))
        let dE = deltaE2000(lab1, lab2)
        maxDeltaE = max(maxDeltaE, dE)
        sumDeltaE += dE

        for ch in 0..<3 {
            let drift = abs(channel(computed, ch) - patch.rec709EncodedExpected[ch]) * 255.0
            maxFullFrame = max(maxFullFrame, drift)
            sumFullFrame += drift
            fullFrameCount += 1
        }
    }
    let meanDeltaE = sumDeltaE / Double(patches.count)
    let meanFullFrame = sumFullFrame / Double(fullFrameCount)

    try expect(maxDeltaE <= 2.0, "D-Log M Macbeth ΔE2000 max = \(maxDeltaE) exceeds budget 2.0")
    try expect(meanDeltaE <= 1.0, "D-Log M Macbeth ΔE2000 mean = \(meanDeltaE) exceeds budget 1.0")
    try expect(maxFullFrame <= 2.0, "D-Log M full-frame max = \(maxFullFrame)/255 exceeds budget 2/255")
    try expect(meanFullFrame <= 0.5, "D-Log M full-frame mean = \(meanFullFrame)/255 exceeds budget 0.5/255")
    print(String(format: "    D-Log M Macbeth ΔE2000 max = %.3f mean = %.3f (budget 2.0/1.0)", maxDeltaE, meanDeltaE))
    print(String(format: "    D-Log M Macbeth full-frame max = %.3f mean = %.3f /255 (budget 2.0/0.5)", maxFullFrame, meanFullFrame))
}

// MARK: - Canon C-Log accuracy gate

private func runClogLinearizationCheck(fixtureURL: URL) throws {
    let samples: [LinearizationSample] = try loadJSON(fixtureURL.appendingPathComponent("linearization-ramp.json"))
    try expect(samples.count == 4096, "C-Log linearization ramp expected 4096 samples, got \(samples.count)")
    var maxDelta = 0.0
    for sample in samples {
        let computed = FilmtoneSourceProfileMath.canonLogDecode(sample.vEncoded)
        maxDelta = max(maxDelta, abs(computed - sample.lLinear))
    }
    try expect(
        maxDelta <= 1e-3,
        "C-Log linearization drift max |Δ| = \(maxDelta) exceeds tolerance 1e-3"
    )
    print(String(format: "    C-Log linearization max |Δ| = %.6f (budget 1e-3)", maxDelta))
}

private func runClogMacbethCheck(fixtureURL: URL) throws {
    let patches: [ClogMacbethPatch] = try loadJSON(fixtureURL.appendingPathComponent("macbeth-patches.json"))
    try expect(patches.count == 24, "C-Log Macbeth fixture expected 24 patches, got \(patches.count)")

    var maxDeltaE = 0.0
    var sumDeltaE = 0.0
    var maxFullFrame = 0.0
    var sumFullFrame = 0.0
    var fullFrameCount = 0

    for patch in patches {
        let computed = FilmtoneSourceProfileMath.canonClogPixelToRec709(
            red: patch.clogEncoded[0],
            green: patch.clogEncoded[1],
            blue: patch.clogEncoded[2]
        )

        let computedLinear = (
            r: rec709InverseEncode(computed.red),
            g: rec709InverseEncode(computed.green),
            b: rec709InverseEncode(computed.blue)
        )
        let expectedLinear = (
            r: rec709InverseEncode(patch.rec709EncodedExpected[0]),
            g: rec709InverseEncode(patch.rec709EncodedExpected[1]),
            b: rec709InverseEncode(patch.rec709EncodedExpected[2])
        )
        let lab1 = xyzToLab(rec709LinearToXYZ(computedLinear))
        let lab2 = xyzToLab(rec709LinearToXYZ(expectedLinear))
        let dE = deltaE2000(lab1, lab2)
        maxDeltaE = max(maxDeltaE, dE)
        sumDeltaE += dE

        for ch in 0..<3 {
            let drift = abs(channel(computed, ch) - patch.rec709EncodedExpected[ch]) * 255.0
            maxFullFrame = max(maxFullFrame, drift)
            sumFullFrame += drift
            fullFrameCount += 1
        }
    }
    let meanDeltaE = sumDeltaE / Double(patches.count)
    let meanFullFrame = sumFullFrame / Double(fullFrameCount)

    try expect(maxDeltaE <= 2.0, "C-Log Macbeth ΔE2000 max = \(maxDeltaE) exceeds budget 2.0")
    try expect(meanDeltaE <= 1.0, "C-Log Macbeth ΔE2000 mean = \(meanDeltaE) exceeds budget 1.0")
    try expect(maxFullFrame <= 2.0, "C-Log full-frame max = \(maxFullFrame)/255 exceeds budget 2/255")
    try expect(meanFullFrame <= 0.5, "C-Log full-frame mean = \(meanFullFrame)/255 exceeds budget 0.5/255")
    print(String(format: "    C-Log Macbeth ΔE2000 max = %.3f mean = %.3f (budget 2.0/1.0)", maxDeltaE, meanDeltaE))
    print(String(format: "    C-Log Macbeth full-frame max = %.3f mean = %.3f /255 (budget 2.0/0.5)", maxFullFrame, meanFullFrame))
}

// MARK: - Canon Log 3 + Cinema Gamut accuracy gate

private func runClog3CineGamutLinearizationCheck(fixtureURL: URL) throws {
    let samples: [LinearizationSample] = try loadJSON(fixtureURL.appendingPathComponent("linearization-ramp.json"))
    try expect(samples.count == 4096, "C-Log 3 linearization ramp expected 4096 samples, got \(samples.count)")
    var maxDelta = 0.0
    for sample in samples {
        let computed = FilmtoneSourceProfileMath.canonLog3Decode(sample.vEncoded)
        maxDelta = max(maxDelta, abs(computed - sample.lLinear))
    }
    try expect(
        maxDelta <= 1e-3,
        "C-Log 3 linearization drift max |Δ| = \(maxDelta) exceeds tolerance 1e-3"
    )
    print(String(format: "    C-Log 3 linearization max |Δ| = %.6f (budget 1e-3)", maxDelta))
}

private func runClog3CineGamutMacbethCheck(fixtureURL: URL) throws {
    let patches: [Clog3CineGamutMacbethPatch] = try loadJSON(fixtureURL.appendingPathComponent("macbeth-patches.json"))
    try expect(patches.count == 24, "C-Log 3 Macbeth fixture expected 24 patches, got \(patches.count)")

    var maxDeltaE = 0.0
    var sumDeltaE = 0.0
    var maxFullFrame = 0.0
    var sumFullFrame = 0.0
    var fullFrameCount = 0

    for patch in patches {
        let computed = FilmtoneSourceProfileMath.canonLog3CineGamutPixelToRec709(
            red: patch.clog3Encoded[0],
            green: patch.clog3Encoded[1],
            blue: patch.clog3Encoded[2]
        )

        let computedLinear = (
            r: rec709InverseEncode(computed.red),
            g: rec709InverseEncode(computed.green),
            b: rec709InverseEncode(computed.blue)
        )
        let expectedLinear = (
            r: rec709InverseEncode(patch.rec709EncodedExpected[0]),
            g: rec709InverseEncode(patch.rec709EncodedExpected[1]),
            b: rec709InverseEncode(patch.rec709EncodedExpected[2])
        )
        let lab1 = xyzToLab(rec709LinearToXYZ(computedLinear))
        let lab2 = xyzToLab(rec709LinearToXYZ(expectedLinear))
        let dE = deltaE2000(lab1, lab2)
        maxDeltaE = max(maxDeltaE, dE)
        sumDeltaE += dE

        for ch in 0..<3 {
            let drift = abs(channel(computed, ch) - patch.rec709EncodedExpected[ch]) * 255.0
            maxFullFrame = max(maxFullFrame, drift)
            sumFullFrame += drift
            fullFrameCount += 1
        }
    }
    let meanDeltaE = sumDeltaE / Double(patches.count)
    let meanFullFrame = sumFullFrame / Double(fullFrameCount)

    try expect(maxDeltaE <= 2.0, "C-Log 3 Macbeth ΔE2000 max = \(maxDeltaE) exceeds budget 2.0")
    try expect(meanDeltaE <= 1.0, "C-Log 3 Macbeth ΔE2000 mean = \(meanDeltaE) exceeds budget 1.0")
    try expect(maxFullFrame <= 2.0, "C-Log 3 full-frame max = \(maxFullFrame)/255 exceeds budget 2/255")
    try expect(meanFullFrame <= 0.5, "C-Log 3 full-frame mean = \(meanFullFrame)/255 exceeds budget 0.5/255")
    print(String(format: "    C-Log 3 Macbeth ΔE2000 max = %.3f mean = %.3f (budget 2.0/1.0)", maxDeltaE, meanDeltaE))
    print(String(format: "    C-Log 3 Macbeth full-frame max = %.3f mean = %.3f /255 (budget 2.0/0.5)", maxFullFrame, meanFullFrame))
}

// MARK: - V-Log accuracy gate (Phase B-3)

private func runVlogLinearizationCheck(fixtureURL: URL) throws {
    let samples: [LinearizationSample] = try loadJSON(fixtureURL.appendingPathComponent("linearization-ramp.json"))
    try expect(samples.count == 4096, "V-Log linearization ramp expected 4096 samples, got \(samples.count)")
    var maxDelta = 0.0
    for sample in samples {
        let computed = FilmtoneSourceProfileMath.vlogDecode(sample.vEncoded)
        maxDelta = max(maxDelta, abs(computed - sample.lLinear))
    }
    try expect(
        maxDelta <= 1e-3,
        "V-Log linearization drift max |Δ| = \(maxDelta) exceeds tolerance 1e-3"
    )
    print(String(format: "    V-Log linearization max |Δ| = %.6f (budget 1e-3)", maxDelta))
}

private func runVlogMacbethCheck(fixtureURL: URL) throws {
    let patches: [MacbethPatch] = try loadJSON(fixtureURL.appendingPathComponent("macbeth-patches.json"))
    try expect(patches.count == 24, "Macbeth fixture expected 24 patches, got \(patches.count)")

    var maxDeltaE = 0.0
    var sumDeltaE = 0.0
    var maxFullFrame = 0.0
    var sumFullFrame = 0.0
    var fullFrameCount = 0

    for patch in patches {
        let computed = FilmtoneSourceProfileMath.vlogPixelToRec709(
            red: patch.vlogEncoded[0],
            green: patch.vlogEncoded[1],
            blue: patch.vlogEncoded[2]
        )

        // Compare Swift's pipeline output against Python's pipeline output
        // — both have the Filmtone shoulder applied. The bare X-Rite
        // linear reference (patch.rec709LinearReference) is retained in
        // the fixture for diagnostics only; comparing post-shoulder Swift
        // output against pre-shoulder X-Rite would always drift by exactly
        // the shoulder transformation. ΔE2000 happens in linear Lab via
        // inverse-Rec.709 → XYZ → Lab on both sides.
        let computedLinear = (
            r: rec709InverseEncode(computed.red),
            g: rec709InverseEncode(computed.green),
            b: rec709InverseEncode(computed.blue)
        )
        let expectedLinear = (
            r: rec709InverseEncode(patch.rec709EncodedExpected[0]),
            g: rec709InverseEncode(patch.rec709EncodedExpected[1]),
            b: rec709InverseEncode(patch.rec709EncodedExpected[2])
        )
        let lab1 = xyzToLab(rec709LinearToXYZ(computedLinear))
        let lab2 = xyzToLab(rec709LinearToXYZ(expectedLinear))
        let dE = deltaE2000(lab1, lab2)
        maxDeltaE = max(maxDeltaE, dE)
        sumDeltaE += dE

        // Full-frame in 8-bit code values: |computed - expected| * 255.
        for ch in 0..<3 {
            let drift = abs(channel(computed, ch) - patch.rec709EncodedExpected[ch]) * 255.0
            maxFullFrame = max(maxFullFrame, drift)
            sumFullFrame += drift
            fullFrameCount += 1
        }
    }
    let meanDeltaE = sumDeltaE / Double(patches.count)
    let meanFullFrame = sumFullFrame / Double(fullFrameCount)

    try expect(
        maxDeltaE <= 2.0,
        "V-Log Macbeth ΔE2000 max = \(maxDeltaE) exceeds budget 2.0"
    )
    try expect(
        meanDeltaE <= 1.0,
        "V-Log Macbeth ΔE2000 mean = \(meanDeltaE) exceeds budget 1.0"
    )
    try expect(
        maxFullFrame <= 2.0,
        "V-Log full-frame max = \(maxFullFrame)/255 exceeds budget 2/255"
    )
    try expect(
        meanFullFrame <= 0.5,
        "V-Log full-frame mean = \(meanFullFrame)/255 exceeds budget 0.5/255"
    )
    print(String(
        format: "    V-Log Macbeth ΔE2000 max = %.3f mean = %.3f (budget 2.0/1.0)",
        maxDeltaE, meanDeltaE
    ))
    print(String(
        format: "    V-Log Macbeth full-frame max = %.3f mean = %.3f /255 (budget 2.0/0.5)",
        maxFullFrame, meanFullFrame
    ))
}

// Rec.709 OETF inverse. Used to back-decode the Swift-computed encoded
// output into linear scene-referred for the ΔE2000 comparison.
private func rec709InverseEncode(_ encoded: Double) -> Double {
    if encoded < 0.018 * 4.5 {
        return encoded / 4.5
    }
    return pow((encoded + 0.099) / 1.099, 1.0 / 0.45)
}

// MARK: - S-Log3 accuracy gate (Phase C)

private func runSlog3LinearizationCheck(fixtureURL: URL) throws {
    let samples: [LinearizationSample] = try loadJSON(fixtureURL.appendingPathComponent("linearization-ramp.json"))
    try expect(samples.count == 4096, "S-Log3 linearization ramp expected 4096 samples, got \(samples.count)")
    var maxDelta = 0.0
    for sample in samples {
        let computed = FilmtoneSourceProfileMath.slog3Decode(sample.vEncoded)
        maxDelta = max(maxDelta, abs(computed - sample.lLinear))
    }
    try expect(
        maxDelta <= 1e-3,
        "S-Log3 linearization drift max |Δ| = \(maxDelta) exceeds tolerance 1e-3"
    )
    print(String(format: "    S-Log3 linearization max |Δ| = %.6f (budget 1e-3)", maxDelta))
}

private func runSlog3MacbethCheck(fixtureURL: URL) throws {
    let patches: [Slog3MacbethPatch] = try loadJSON(fixtureURL.appendingPathComponent("macbeth-patches.json"))
    try expect(patches.count == 24, "S-Log3 Macbeth fixture expected 24 patches, got \(patches.count)")

    var maxDeltaE = 0.0
    var sumDeltaE = 0.0
    var maxFullFrame = 0.0
    var sumFullFrame = 0.0
    var fullFrameCount = 0

    for patch in patches {
        let computed = FilmtoneSourceProfileMath.slog3PixelToRec709(
            red: patch.slog3Encoded[0],
            green: patch.slog3Encoded[1],
            blue: patch.slog3Encoded[2]
        )

        let computedLinear = (
            r: rec709InverseEncode(computed.red),
            g: rec709InverseEncode(computed.green),
            b: rec709InverseEncode(computed.blue)
        )
        let expectedLinear = (
            r: rec709InverseEncode(patch.rec709EncodedExpected[0]),
            g: rec709InverseEncode(patch.rec709EncodedExpected[1]),
            b: rec709InverseEncode(patch.rec709EncodedExpected[2])
        )
        let lab1 = xyzToLab(rec709LinearToXYZ(computedLinear))
        let lab2 = xyzToLab(rec709LinearToXYZ(expectedLinear))
        let dE = deltaE2000(lab1, lab2)
        maxDeltaE = max(maxDeltaE, dE)
        sumDeltaE += dE

        for ch in 0..<3 {
            let drift = abs(channel(computed, ch) - patch.rec709EncodedExpected[ch]) * 255.0
            maxFullFrame = max(maxFullFrame, drift)
            sumFullFrame += drift
            fullFrameCount += 1
        }
    }
    let meanDeltaE = sumDeltaE / Double(patches.count)
    let meanFullFrame = sumFullFrame / Double(fullFrameCount)

    try expect(
        maxDeltaE <= 2.0,
        "S-Log3 Macbeth ΔE2000 max = \(maxDeltaE) exceeds budget 2.0"
    )
    try expect(
        meanDeltaE <= 1.0,
        "S-Log3 Macbeth ΔE2000 mean = \(meanDeltaE) exceeds budget 1.0"
    )
    try expect(
        maxFullFrame <= 2.0,
        "S-Log3 full-frame max = \(maxFullFrame)/255 exceeds budget 2/255"
    )
    try expect(
        meanFullFrame <= 0.5,
        "S-Log3 full-frame mean = \(meanFullFrame)/255 exceeds budget 0.5/255"
    )
    print(String(
        format: "    S-Log3 Macbeth ΔE2000 max = %.3f mean = %.3f (budget 2.0/1.0)",
        maxDeltaE, meanDeltaE
    ))
    print(String(
        format: "    S-Log3 Macbeth full-frame max = %.3f mean = %.3f /255 (budget 2.0/0.5)",
        maxFullFrame, meanFullFrame
    ))
}

// Channel access helper for the (red, green, blue) tuple returned by
// `vlogPixelToRec709`. Tuple extensions are still experimental in Swift, so
// the test uses a free function instead.
private func channel(_ tuple: (red: Double, green: Double, blue: Double), _ i: Int) -> Double {
    switch i {
    case 0: return tuple.red
    case 1: return tuple.green
    case 2: return tuple.blue
    default: fatalError("invalid channel index \(i)")
    }
}

// MARK: - Entry point

@main
struct TestSourceProfileMath {
    static func main() throws {
        let args = Array(CommandLine.arguments.dropFirst())
        try expect(args.count >= 1, "usage: test-source-profile-math <fixtures-root>")
        let fixturesRoot = URL(fileURLWithPath: args[0])

        let dlogFixture = fixturesRoot.appendingPathComponent("dji-dlog")
        if FileManager.default.fileExists(atPath: dlogFixture.path) {
            print("==> D-Log accuracy gate")
            try runDlogLinearizationCheck(fixtureURL: dlogFixture)
            try runDlogMacbethCheck(fixtureURL: dlogFixture)
        }
        let dlogmFixture = fixturesRoot.appendingPathComponent("dji-dlog-m")
        if FileManager.default.fileExists(atPath: dlogmFixture.path) {
            print("==> D-Log M + D-Gamut M accuracy gate")
            try runDlogMLinearizationCheck(fixtureURL: dlogmFixture)
            try runDlogMMacbethCheck(fixtureURL: dlogmFixture)
        }
        let clogFixture = fixturesRoot.appendingPathComponent("canon-clog")
        if FileManager.default.fileExists(atPath: clogFixture.path) {
            print("==> C-Log accuracy gate")
            try runClogLinearizationCheck(fixtureURL: clogFixture)
            try runClogMacbethCheck(fixtureURL: clogFixture)
        }
        let clog3Fixture = fixturesRoot.appendingPathComponent("canon-log3-cinema-gamut")
        if FileManager.default.fileExists(atPath: clog3Fixture.path) {
            print("==> C-Log 3 + Cinema Gamut accuracy gate")
            try runClog3CineGamutLinearizationCheck(fixtureURL: clog3Fixture)
            try runClog3CineGamutMacbethCheck(fixtureURL: clog3Fixture)
        }
        let vlogFixture = fixturesRoot.appendingPathComponent("panasonic-vlog")
        if FileManager.default.fileExists(atPath: vlogFixture.path) {
            print("==> V-Log accuracy gate")
            try runVlogLinearizationCheck(fixtureURL: vlogFixture)
            try runVlogMacbethCheck(fixtureURL: vlogFixture)
        }
        let slog3Fixture = fixturesRoot.appendingPathComponent("sony-slog3")
        if FileManager.default.fileExists(atPath: slog3Fixture.path) {
            print("==> S-Log3 accuracy gate")
            try runSlog3LinearizationCheck(fixtureURL: slog3Fixture)
            try runSlog3MacbethCheck(fixtureURL: slog3Fixture)
        }
        print("Source profile math tests passed")
    }
}
