import type { Phase0Params } from "./phase0-schema";

/**
 * iOS Phase 0 ships with a deliberately small preset set.
 *
 * Shared PRESETS remain the canonical Desktop/Web defaults. iOS uses these
 * mobile-specific patches over Filmtone's soft default base so the phone app
 * has fewer, clearer choices without changing other product surfaces.
 */
export const FILMTONE_IOS_PRESET_NAMES = [
  "reset",
  "iphone",
  "softBlue",
  "amberGlow",
] as const;

export type FilmtoneIosPresetName =
  (typeof FILMTONE_IOS_PRESET_NAMES)[number];

export const FILMTONE_IOS_PRESET_PATCHES = {
  iphone: {
    exposure: 0.04,
    contrast: 1.08,
    saturation: 0.94,
    temperature: 0.02,
    tint: 0.0,
    rgbShift: 0.0006,
    lensSoftness: 0.035,
    grainSize: 0.26,
    bloomThreshold: 0.76,
    bloomStrength: 0.18,
    bloomRadius: 0.48,
    diffusion: 0.08,
    halationIntensity: 0.06,
    halationSpread: 18,
    halationHue: 22,
    halationRadius: 0.38,
    compressionAmount: 0.18,
    compressionRange: 0.68,
    printContrast: 0.06,
    fade: 0.02,
    vignette: 0.18,
    grainIntensity: 0.025,
  },
  softBlue: {
    exposure: 0.16,
    contrast: 0.94,
    saturation: 1.08,
    temperature: -0.18,
    tint: -0.04,
    rgbShift: 0.0008,
    lensSoftness: 0.1,
    grainSize: 0.34,
    bloomThreshold: 0.62,
    bloomStrength: 0.36,
    bloomRadius: 0.72,
    diffusion: 0.24,
    halationIntensity: 0.08,
    halationSpread: 24,
    halationHue: 18,
    halationThreshold: 0.54,
    halationRadius: 0.5,
    bloomSoftKnee: 0.72,
    halationSoftKnee: 0.42,
    compressionAmount: 0.32,
    compressionRange: 0.82,
    printContrast: 0.04,
    cyan: 0.05,
    magenta: -0.03,
    yellow: -0.06,
    fade: 0.1,
    vignette: 0.16,
    grainIntensity: 0.035,
  },
  amberGlow: {
    exposure: 0.08,
    contrast: 1.12,
    saturation: 1.12,
    temperature: 0.26,
    tint: 0.02,
    rgbShift: 0.001,
    lensSoftness: 0.05,
    grainSize: 0.32,
    bloomThreshold: 0.68,
    bloomStrength: 0.24,
    bloomRadius: 0.5,
    diffusion: 0.12,
    halationIntensity: 0.14,
    halationSpread: 22,
    halationHue: 30,
    halationThreshold: 0.52,
    halationRadius: 0.46,
    bloomSoftKnee: 0.62,
    halationSoftKnee: 0.44,
    compressionAmount: 0.14,
    compressionRange: 0.64,
    printContrast: 0.1,
    cyan: -0.08,
    magenta: 0.03,
    yellow: 0.12,
    fade: 0.04,
    vignette: 0.22,
    grainIntensity: 0.045,
  },
} satisfies Partial<Record<FilmtoneIosPresetName, Partial<Phase0Params>>>;
