import {
  IOS_OPTICAL_FILTER_OPTICAL_KEYS,
  IOS_OPTICAL_FILTER_PAYLOAD,
  IOS_OPTICAL_FILTER_SPATIAL_KEYS,
  type IosOpticalFilterProfilePayload,
} from "./ios-optical-filter-payload";

function renderSwiftString(value: string): string {
  return JSON.stringify(value);
}

function renderSwiftNumber(value: number): string {
  if (Number.isInteger(value)) {
    return value.toFixed(1);
  }
  const rendered = value.toString();
  return rendered.includes("e") ? value.toFixed(8) : rendered;
}

function renderOpticalKeys(
  optical: IosOpticalFilterProfilePayload["optical"],
  indent: string,
): string {
  const inner = indent + "    ";
  const lines = IOS_OPTICAL_FILTER_OPTICAL_KEYS.map((key, index) => {
    const suffix =
      index === IOS_OPTICAL_FILTER_OPTICAL_KEYS.length - 1 ? "" : ",";
    return `${inner}${key}: ${renderSwiftNumber(optical[key])}${suffix}`;
  });
  return ["OpticalKeys(", lines.join("\n"), `${indent})`].join("\n");
}

function renderSpatialKeys(
  spatial: IosOpticalFilterProfilePayload["spatial"],
  indent: string,
): string {
  const inner = indent + "    ";
  const lines = IOS_OPTICAL_FILTER_SPATIAL_KEYS.map((key, index) => {
    const suffix =
      index === IOS_OPTICAL_FILTER_SPATIAL_KEYS.length - 1 ? "" : ",";
    return `${inner}${key}: ${renderSwiftNumber(spatial[key])}${suffix}`;
  });
  return ["SpatialKeys(", lines.join("\n"), `${indent})`].join("\n");
}

function renderProfile(
  profile: IosOpticalFilterProfilePayload,
  indent: string,
): string {
  const fieldIndent = indent + "    ";
  const opticalSwift = renderOpticalKeys(profile.optical, fieldIndent);
  const spatialSwift = renderSpatialKeys(profile.spatial, fieldIndent);
  return [
    "Profile(",
    `${fieldIndent}id: ${renderSwiftString(profile.id)},`,
    `${fieldIndent}family: ${renderSwiftString(profile.family)},`,
    `${fieldIndent}density: ${renderSwiftString(profile.density)},`,
    `${fieldIndent}displayName: ${renderSwiftString(profile.displayName)},`,
    `${fieldIndent}shortLabel: ${renderSwiftString(profile.shortLabel)},`,
    `${fieldIndent}optical: ${opticalSwift},`,
    `${fieldIndent}spatial: ${spatialSwift}`,
    `${indent})`,
  ].join("\n");
}

export function renderFilmtoneIosOpticalFiltersSwift(
  payload: readonly IosOpticalFilterProfilePayload[] = IOS_OPTICAL_FILTER_PAYLOAD,
): string {
  const backlightVeilEntries = payload.filter(
    (profile) => profile.family === "backlightVeil",
  );
  const profileIndent = "        ";
  const renderedProfiles = backlightVeilEntries
    .map((profile) => `${profileIndent}${renderProfile(profile, profileIndent)}`)
    .join(",\n");

  const opticalFields = IOS_OPTICAL_FILTER_OPTICAL_KEYS.map(
    (key) => `        let ${key}: Double`,
  ).join("\n");
  const spatialFields = IOS_OPTICAL_FILTER_SPATIAL_KEYS.map(
    (key) => `        let ${key}: Double`,
  ).join("\n");

  return `import Foundation

// AUTO-GENERATED by \`bun run generate:ios-swift\` from
// packages/film-lab-core/src/ios-optical-filter-payload.ts (Deep Glow
// compatibility family). Do not edit by hand. Re-run the generator to update.

enum FilmtoneOpticalFiltersGenerated {
    struct OpticalKeys: Equatable, Sendable {
${opticalFields}
    }

    struct SpatialKeys: Equatable, Sendable {
${spatialFields}
    }

    struct Profile: Equatable, Sendable {
        let id: String
        let family: String
        let density: String
        let displayName: String
        let shortLabel: String
        let optical: OpticalKeys
        let spatial: SpatialKeys
    }

    static let backlightVeilProfiles: [Profile] = [
${renderedProfiles}
    ]
}
`;
}
