import { PARAM_KEYS, cloneParams, type Params } from "./params";
import {
  FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
  FILM_LAB_DEFAULT_SHADOW_HUE,
} from "./split-tone-default-hues";

export type ContractDefaultKey =
  | "depthMistGain"
  | "depthGlowGain"
  | "depthRayAngleGamma"
  | "depthRayAngleInnerThreshold"
  | "depthMistRayAngleGain"
  | "depthBloomRayAngleGain"
  | "depthHalationRayAngleGain"
  | "depthMistFieldPsfGain"
  | "depthBloomFieldPsfGain"
  | "depthHalationFieldPsfGain"
  | "depthMistFieldPsfRadiusPx"
  | "depthBloomFieldPsfRadiusPx"
  | "depthHalationFieldPsfRadiusPx"
  | "crossFilterDepthGain"
  | "crossFilterAngleGain"
  | "crossFilterAngleGamma"
  | "crossFilterAngleInnerThreshold"
  | "crossFilterEdgeLengthGain"
  | "crossFilterEdgeStrengthGain"
  | "haloPrismStrength"
  | "haloPrismRadius"
  | "haloPrismWidth"
  | "haloPrismChromatic"
  | "haloPrismThreshold"
  | "haloPrismSplit"
  | "haloPrismAngle"
  | "haloPrismSourceReactivity";

type BasePresetParams = Omit<Params, ContractDefaultKey>;

export const CONTRACT_DEFAULTS: Readonly<Pick<Params, ContractDefaultKey>> = {
  depthMistGain: 0,
  depthGlowGain: 0,
  depthRayAngleGamma: 1.4,
  depthRayAngleInnerThreshold: 0.1,
  depthMistRayAngleGain: 0.35,
  depthBloomRayAngleGain: 0.25,
  depthHalationRayAngleGain: 0.18,
  depthMistFieldPsfGain: 1,
  depthBloomFieldPsfGain: 1,
  depthHalationFieldPsfGain: 1,
  depthMistFieldPsfRadiusPx: 18,
  depthBloomFieldPsfRadiusPx: 9,
  depthHalationFieldPsfRadiusPx: 12,
  crossFilterDepthGain: 0.25,
  crossFilterAngleGain: 0.35,
  crossFilterAngleGamma: 1.4,
  crossFilterAngleInnerThreshold: 0.1,
  crossFilterEdgeLengthGain: 0.45,
  crossFilterEdgeStrengthGain: 0.25,
  haloPrismStrength: 0,
  haloPrismRadius: 0.62,
  haloPrismWidth: 0.22,
  haloPrismChromatic: 0.65,
  haloPrismThreshold: 0.9,
  haloPrismSplit: 0.7,
  haloPrismAngle: 0,
  haloPrismSourceReactivity: 0.85,
} as const;

function withContractDefaults<T extends Record<string, BasePresetParams>>(
  presets: T,
): { [K in keyof T]: Params } {
  return Object.fromEntries(
    Object.entries(presets).map(([name, preset]) => [
      name,
      {
        ...preset,
        ...CONTRACT_DEFAULTS,
      },
    ]),
  ) as { [K in keyof T]: Params };
}

/**
 * 組み込みプリセット（Next Film Lab と同一数値）
 *
 * grainIntensity は 0.10 を安全上限とし、0.10 超えの旧値は schema/runtime で丸める。
 * grainRadialMix は Pro で 0〜1 調整可。プリセット既定は 1（周辺比重オン）。
 * grainSize は 2026-04-22 low-end uplift 以降、低域で actual fine grain が見える前提で調整する。
 */
const RAW_PRESETS = {
  reset: {
    exposure: 0,
    contrast: 1,
    saturation: 1,
    temperature: 0,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0,
    grainRadialMix: 1,
    grainSize: 0.3,
    vignette: 0,
    bloomThreshold: 0.8,
    bloomStrength: 0,
    bloomRadius: 0.4,
    diffusion: 0,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    halationThreshold: 0.6,
    halationRadius: 0.6,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0,
    highlights: 0,
    shadows: 0,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  /**
   * cinematic プリセット（v2・2026-03-31）
   * @description 初見のフィルター感とシアン肌を抑えつつ Teal & Orange の意図は維持。変更理由はリポ外ドキュメントに記載可。
   */
  cinematic: {
    exposure: 0.09,
    contrast: 1.24,
    saturation: 0.87,
    temperature: -0.11,
    tint: 0,
    rgbShift: 0.002,
    lensSoftness: 0,
    grainIntensity: 0.05,
    grainRadialMix: 1,
    grainSize: 0.32,
    vignette: 0.32,
    bloomThreshold: 0.76,
    bloomStrength: 0.26,
    bloomRadius: 0.50,
    diffusion: 0.10,
    halationIntensity: 0.06,
    halationSpread: 20,
    halationHue: 18,
    halationThreshold: 0.6,
    halationRadius: 0.40,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.025,
    highlights: -0.08,
    shadows: -0.11,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  portra: {
    exposure: 0.2,
    contrast: 1.1,
    saturation: 0.9,
    temperature: 0.1,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0.08,
    grainRadialMix: 1,
    grainSize: 0.32,
    vignette: 0.2,
    bloomThreshold: 0.78,
    bloomStrength: 0.14,
    bloomRadius: 0.38,
    diffusion: 0.05,
    halationIntensity: 0.18,
    halationSpread: 20,
    halationHue: 28,
    halationThreshold: 0.6,
    halationRadius: 0.44,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.05,
    highlights: 0,
    shadows: 0.1,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  gold200: {
    exposure: 0.15,
    contrast: 1.2,
    saturation: 1.15,
    temperature: 0.18,
    tint: 0,
    rgbShift: 0.0012,
    lensSoftness: 0,
    grainIntensity: 0.07,
    grainRadialMix: 1,
    grainSize: 0.28,
    vignette: 0.25,
    bloomThreshold: 0.80,
    bloomStrength: 0.16,
    bloomRadius: 0.35,
    diffusion: 0.04,
    halationIntensity: 0.12,
    halationSpread: 18,
    halationHue: 32,
    halationThreshold: 0.6,
    halationRadius: 0.40,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.03,
    highlights: 0.05,
    shadows: 0,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  pro400h: {
    exposure: 0.25,
    contrast: 1.05,
    saturation: 0.85,
    temperature: -0.1,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0.04,
    grainRadialMix: 1,
    grainSize: 0.25,
    vignette: 0.15,
    bloomThreshold: 0.84,
    bloomStrength: 0.06,
    bloomRadius: 0.42,
    diffusion: 0,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    halationThreshold: 0.6,
    halationRadius: 0.30,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.08,
    highlights: 0.05,
    shadows: 0.15,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  bw: {
    exposure: 0.1,
    contrast: 1.4,
    saturation: 0,
    temperature: 0,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0.1,
    grainRadialMix: 1,
    grainSize: 0.43,
    vignette: 0.5,
    bloomThreshold: 0.80,
    bloomStrength: 0.16,
    bloomRadius: 0.52,
    diffusion: 0.04,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    halationThreshold: 0.6,
    halationRadius: 0.30,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.02,
    highlights: -0.1,
    shadows: -0.1,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  ektar100: {
    exposure: 0.05,
    contrast: 1.25,
    saturation: 1.3,
    temperature: 0.02,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0.03,
    grainRadialMix: 1,
    grainSize: 0.12,
    vignette: 0.15,
    bloomThreshold: 0.86,
    bloomStrength: 0.08,
    bloomRadius: 0.28,
    diffusion: 0,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    halationThreshold: 0.6,
    halationRadius: 0.30,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0,
    highlights: 0.1,
    shadows: -0.1,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  superia400: {
    exposure: 0.1,
    contrast: 1.18,
    saturation: 1.08,
    temperature: -0.08,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0.065,
    grainRadialMix: 1,
    grainSize: 0.40,
    vignette: 0.2,
    bloomThreshold: 0.8,
    bloomStrength: 0.08,
    bloomRadius: 0.32,
    diffusion: 0,
    halationIntensity: 0.08,
    halationSpread: 15,
    halationHue: 14,
    halationThreshold: 0.6,
    halationRadius: 0.32,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.04,
    highlights: 0,
    shadows: 0.05,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  cinestill800t: {
    exposure: 0.15,
    contrast: 1.15,
    saturation: 0.95,
    temperature: -0.3,
    tint: 0,
    rgbShift: 0.00115,
    lensSoftness: 0,
    grainIntensity: 0.08,
    grainRadialMix: 1,
    grainSize: 0.58,
    vignette: 0.3,
    bloomThreshold: 0.64,
    bloomStrength: 0.40,
    bloomRadius: 0.60,
    diffusion: 0.16,
    halationIntensity: 0.14,
    halationSpread: 28,
    halationHue: 20,
    halationThreshold: 0.6,
    halationRadius: 0.56,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0.03,
    highlights: -0.05,
    shadows: 0,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
  /**
   * Velvia 50 プリセット（v1・2026-04-02）
   * @description Fujifilm Velvia 50 スライドポジフィルム。高彩度・高コントラスト・極細粒・ハレーションなし。
   * fade=0 でポジらしい黒沈みを表現。saturation/contrast は Velvia の代名詞の鮮烈さに合わせた。
   */
  velvia50: {
    exposure: 0,
    contrast: 1.35,
    saturation: 1.45,
    temperature: 0.04,
    tint: 0,
    rgbShift: 0,
    lensSoftness: 0,
    grainIntensity: 0.01,
    grainRadialMix: 1,
    grainSize: 0.08,
    vignette: 0.1,
    bloomThreshold: 0.9,
    bloomStrength: 0.04,
    bloomRadius: 0.28,
    diffusion: 0,
    halationIntensity: 0,
    halationSpread: 15,
    halationHue: 0,
    halationThreshold: 0.6,
    halationRadius: 0.30,
    bloomSoftKnee: 0.5,
    halationSoftKnee: 0.3,
    fade: 0,
    highlights: 0.05,
    shadows: -0.05,
    shadowTone: 0,
    highlightTone: 0,
    shadowHue: FILM_LAB_DEFAULT_SHADOW_HUE,
    highlightHue: FILM_LAB_DEFAULT_HIGHLIGHT_HUE,
    compressionAmount: 0,
    compressionRange: 0.5,
    printContrast: 0,
    cyan: 0,
    magenta: 0,
    yellow: 0,
    motionBlurAmount: 0,
    shutterAngle: 0,
    trailIntensity: 0,
    dustAmount: 0,
    scratchAmount: 0,
    shaftIntensity: 0,
    shaftDecay: 0.5,
    shaftOriginX: 0.5,
    shaftOriginY: 0.15,
    crossFilterStrength: 0,
    crossFilterSpikes: 4,
    crossFilterAngle: 0,
    crossFilterLength: 0.4,
    crossFilterThreshold: 0.92,
    crossFilterChromatic: 0.3,
    crossFilterSizeLimit: 0,
    crossFilterRandomness: 1,
    crossFilterHardMode: 1,
    crossFilterMinSpacing: 1,
  },
} satisfies Record<string, BasePresetParams>;

export const PRESETS = withContractDefaults(RAW_PRESETS);

export type PresetName = keyof typeof PRESETS;

export const FILMTONE_DEFAULT_BASE_PRESET = "reset" satisfies PresetName;

export const FILMTONE_SOFT_FINISH_PATCH = {
  bloomStrength: 0.22,
  bloomThreshold: 0.72,
  bloomRadius: 0.52,
  diffusion: 0.08,
  halationIntensity: 0.10,
  halationSpread: 22,
  halationRadius: 0.44,
  halationHue: 20,
} satisfies Partial<Params>;

export function createFilmtoneDefaultParams(): Params {
  return Object.assign(
    cloneParams(PRESETS[FILMTONE_DEFAULT_BASE_PRESET]),
    FILMTONE_SOFT_FINISH_PATCH,
  );
}

/**
 * プリセットの数値が、今の Params と**全部同じ**かを調べる。
 *
 * 概要: URL 共有や保存データの Params から、どの組み込みプリセットに一致するかを逆引きする。
 * 仕様: `PARAM_KEYS` に並ぶキーを順番に比較し、完全一致した最初のプリセット名を返す。
 * 制限: 少しでも数値が違うと一致扱いにしない。近い値を「だいたい同じ」とは判定しない。
 *
 * @param params - 照合したい Film Lab のパラメータ
 */
export function findMatchingPreset(params: Params): PresetName | null {
  for (const [name, preset] of Object.entries(PRESETS) as [PresetName, Params][]) {
    if (PARAM_KEYS.every((key) => preset[key] === params[key])) {
      return name;
    }
  }
  return null;
}

/**
 * プリセットバーに並べる表示用メタ情報。
 *
 * 概要: ボタンの見出し・短い説明文・カテゴリ分類・Print Medium ドキュメントをまとめ、
 *       Web / Desktop で同じ順番・同じ文言を使えるようにする。
 * 仕様: `name` は `PRESETS` のキーと一致し、UI はこの配列順で表示できる。
 * 制限: 見た目用の文言とメタ情報のみ。数値パラメータ自体は `PRESETS` を参照する。
 *
 * category:
 *   - "filmStock"  : 実フィルムのエミュレーション。Film Stock セレクターに表示する。
 *   - "look"       : フィルムではないスタイル（Teal & Orange 等）。Film Stock とは別枠。
 *   - "utility"    : reset など。セレクターの外側に配置する。
 *
 * printMedium (ドキュメント用・シリアライズしない):
 *   各プリセットが暗黙的に想定している印画媒体。UI に出さず、将来の Print Medium 独立 UI への橋渡し用。
 */
export const PRESET_BUTTONS: {
  name: PresetName;
  label: string;
  subtitle: string;
  category: "filmStock" | "look" | "utility";
  printMedium?: "color_negative" | "silver_gelatin" | "tungsten_cinema" | "slide_positive";
}[] = [
  { name: "reset", label: "Neutral", subtitle: "Clean Base", category: "utility" },
  { name: "portra", label: "Portra 400", subtitle: "Warm Pastel", category: "filmStock", printMedium: "color_negative" },
  { name: "gold200", label: "Gold 200", subtitle: "Saturated Warm", category: "filmStock", printMedium: "color_negative" },
  { name: "pro400h", label: "Pro 400H", subtitle: "Cool Soft", category: "filmStock", printMedium: "color_negative" },
  { name: "ektar100", label: "Ektar 100", subtitle: "Vivid Sharp", category: "filmStock", printMedium: "color_negative" },
  { name: "superia400", label: "Superia 400", subtitle: "Cool Green", category: "filmStock", printMedium: "color_negative" },
  { name: "cinestill800t", label: "CineStill 800T", subtitle: "Tungsten Glow", category: "filmStock", printMedium: "tungsten_cinema" },
  { name: "bw", label: "B&W", subtitle: "Classic Mono", category: "filmStock", printMedium: "silver_gelatin" },
  { name: "velvia50", label: "Velvia 50", subtitle: "Vivid Slide", category: "filmStock", printMedium: "slide_positive" },
  { name: "cinematic", label: "Cinematic", subtitle: "Teal & Orange", category: "look" },
];
