import Foundation

// AUTO-GENERATED by `bun run generate:ios-swift` from
// packages/film-lab-core/src/ios-optical-filter-payload.ts (Deep Glow
// compatibility family). Do not edit by hand. Re-run the generator to update.

enum FilmtoneOpticalFiltersGenerated {
    struct OpticalKeys: Equatable, Sendable {
        let directTransmission: Double
        let blackRetention: Double
        let scatterStrength: Double
        let highlightReactivity: Double
        let warmScatter: Double
        let spectralTail: Double
    }

    struct SpatialKeys: Equatable, Sendable {
        let bloomThreshold: Double
        let bloomStrength: Double
        let bloomRadius: Double
        let bloomSoftKnee: Double
        let diffusion: Double
        let halationIntensity: Double
        let halationThreshold: Double
        let halationRadius: Double
        let halationHue: Double
        let halationSoftKnee: Double
        let lensSoftness: Double
        let rgbShift: Double
    }

    struct Profile: Equatable, Sendable {
        let id: String
        let family: String
        let density: String
        let displayName: String
        let shortLabel: String
        let optical: OpticalKeys
        let spatial: SpatialKeys
    }

    static let backlightVeilProfiles: [Profile] = [
        Profile(
            id: "backlightVeil-1-8",
            family: "backlightVeil",
            density: "1/8",
            displayName: "Deep Glow - Subtle",
            shortLabel: "Subtle",
            optical: OpticalKeys(
                directTransmission: 0.92,
                blackRetention: 0.78,
                scatterStrength: 0.42,
                highlightReactivity: 0.62,
                warmScatter: 0.1,
                spectralTail: 0.04
            ),
            spatial: SpatialKeys(
                bloomThreshold: 0.66,
                bloomStrength: 0.2,
                bloomRadius: 0.7,
                bloomSoftKnee: 0.7,
                diffusion: 0.12,
                halationIntensity: 0.07,
                halationThreshold: 0.58,
                halationRadius: 0.52,
                halationHue: 22.0,
                halationSoftKnee: 0.48,
                lensSoftness: 0.06,
                rgbShift: 0.0005
            )
        ),
        Profile(
            id: "backlightVeil-1-4",
            family: "backlightVeil",
            density: "1/4",
            displayName: "Deep Glow - Balanced",
            shortLabel: "Balanced",
            optical: OpticalKeys(
                directTransmission: 0.81,
                blackRetention: 0.56,
                scatterStrength: 0.66,
                highlightReactivity: 0.78,
                warmScatter: 0.17,
                spectralTail: 0.07
            ),
            spatial: SpatialKeys(
                bloomThreshold: 0.56,
                bloomStrength: 0.38,
                bloomRadius: 0.8,
                bloomSoftKnee: 0.76,
                diffusion: 0.24,
                halationIntensity: 0.14,
                halationThreshold: 0.52,
                halationRadius: 0.62,
                halationHue: 22.0,
                halationSoftKnee: 0.56,
                lensSoftness: 0.08,
                rgbShift: 0.0007
            )
        ),
        Profile(
            id: "backlightVeil-1-2",
            family: "backlightVeil",
            density: "1/2",
            displayName: "Deep Glow - Strong",
            shortLabel: "Strong",
            optical: OpticalKeys(
                directTransmission: 0.7,
                blackRetention: 0.36,
                scatterStrength: 0.9,
                highlightReactivity: 0.95,
                warmScatter: 0.24,
                spectralTail: 0.1
            ),
            spatial: SpatialKeys(
                bloomThreshold: 0.5,
                bloomStrength: 0.6,
                bloomRadius: 0.88,
                bloomSoftKnee: 0.82,
                diffusion: 0.38,
                halationIntensity: 0.22,
                halationThreshold: 0.46,
                halationRadius: 0.74,
                halationHue: 22.0,
                halationSoftKnee: 0.64,
                lensSoftness: 0.1,
                rgbShift: 0.0009
            )
        )
    ]
}
