metadata_path("./fastlane/metadata")
screenshots_path("./fastlane/screenshots")
languages(["ja", "en-US"])
primary_category("PHOTO_AND_VIDEO")

skip_metadata(false)
skip_screenshots(true)
skip_binary_upload(true)

automatic_release(false)
force(true)
submission_information(
  {
    export_compliance_uses_encryption: false,
  }
)
